# Generated by Django 5.2 on 2025-04-10 09:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                (
                    'language',
                    models.CharField(
                        choices=[('en', 'Английский'), ('ru', 'Русский'), ('it', 'Итальянский'), ('sl', 'Словенский')],
                        default='en',
                        max_length=2,
                    ),
                ),
                (
                    'topic',
                    models.CharField(
                        blank=True,
                        choices=[('legal', 'Legal Framework'), ('cases', 'Case Studies'), ('news', 'News & Updates')],
                        default='news',
                        max_length=20,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='File')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Display name')),
                (
                    'article',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='articles.article'
                    ),
                ),
            ],
        ),
    ]
